services:
  postgres:
    image: postgres:17
    container_name: idt-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "userdb" ]
      interval: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - idt-network

  frontend:
    build:
      context: ./frontend
    container_name: idt-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - idt-network

volumes:
  postgres_data:

networks:
  idt-network:
    driver: bridge