name: Build and Push to ECR
on:
  workflow_dispatch:
  repository_dispatch:
    types: [ready-to-build]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-west-2
        
    - name: Generate image tag
      run: echo "IMAGE_TAG=$(date +%Y%m%d-%H%M)-qa" >> $GITHUB_ENV
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Confirm Docker Exists
      run: docker --version
      
    - name: Docker login to ECR
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      run: |
        aws ecr get-login-password --region us-west-2 | \
        docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com"
        
    - name: Make build script executable
      run: chmod +x build-and-push.sh
      
    - name: Build, tag, and push images
      env:
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      run: ./build-and-push.sh "$IMAGE_TAG" "$AWS_ACCOUNT_ID"
