name: Build and Push to ECR

on:
  # 03:00 AM PT (10:00 UTC)
  schedule:
    - cron: '0 10 * * *'

  # Manual “Run workflow”
  workflow_dispatch:
    inputs:
      build_all:
        description: "Build EVERY service (ignore change detection)?"
        required: false
        default: "false"
        type: choice
        options: ["false", "true"]

env:
  REGION: us-west-2
  SERVICES_JSON: '["frontend","list-service","email-service","metric-service"]'

jobs:
  detect-changes:
    if: ${{ github.event.inputs.build_all != 'true' }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v44
        id: chg
        with:
          dir_names: |
            frontend
            backend/list-service
            backend/email-service
            backend/metric-service

      - name: Build service list JSON
        id: set
        run: |
          CHANGED=$(echo "${{ steps.chg.outputs.all_changed_and_modified_files }}" \
            | tr ' ' '\n' | cut -d/ -f1-2 | sort -u \
            | sed -E 's#^(frontend)$#\1#;s#^backend/##;s#/.+$##')
          jq -n --arg s "$CHANGED" '$s|split("\n")|map(select(. != ""))' > tmp.json
          echo "matrix=$(cat tmp.json)" >> $GITHUB_OUTPUT
          echo "::notice title=Matrix::$(cat tmp.json)"

