name: Build and Push to ECR

on:
  # 03:00 AM PT (10:00 UTC)
  schedule:
    - cron: '0 10 * * *'

  # Manual “Run workflow”
  workflow_dispatch:
    inputs:
      build_all:
        description: "Build EVERY service (ignore change detection)?"
        required: false
        default: "false"
        type: choice
        options: ["false", "true"]

env:
  REGION: us-west-2
  SERVICES_JSON: '["frontend","list-service","email-service","metric-service"]'

jobs:
  detect-changes:
    if: ${{ github.event.inputs.build_all != 'true' }}
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          dir_names: "true"

      - name: List all changed directories
        env:
          ALL_CHANGED_DIRS: ${{ steps.changed-files.outputs.all_changed_files }} # works for dirs
        run: |
          for dir in ${ALL_CHANGED_DIRS}; do
            echo "$dir was changed"
          done

