name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (qa, uat, prod)'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - uat
          - prod

jobs:
  release:
    name: Release with Environment Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Set environment variable
        run: echo "ENVIRONMENT=${{ github.event.inputs.environment || 'qa' }}" >> $GITHUB_ENV

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENVIRONMENT: ${{ env.ENVIRONMENT }}
        run: npx semantic-release